import subprocess
import pyautogui as pag
import time

subprocess.run('C:\\Users\\ksraj\\OneDrive\\Desktop\\saplogon.bat',shell=True)
time.sleep(20)
pag.hotkey('alt','space')
time.sleep(5)
pag.press('x')
time.sleep(5)
pag.write('yfr117')
time.sleep(3)
pag.press('enter')
time.sleep(2)
pag.write('4200')
time.sleep(2)
pag.press('down',presses=3)
time.sleep(1)
pag.press('tab',presses=2)
time.sleep(1)
pag.press('space')
time.sleep(1)
pag.hotkey('ctrl','tab')
time.sleep(1)
pag.press('tab',presses=10)
time.sleep(1)
pag.press('space')
time.sleep(1)
pag.press('f8')
time.sleep(8)
pag.press('tab',presses=11)
# pag.write((pag.prompt(text='Enter location code With R Prefix', title='MSG Box' , default='')))
pag.write('R191384')
time.sleep(2)
pag.press('tab',presses=9)
time.sleep(2)
pag.write('0010')
time.sleep(2)
pag.press('f8')
time.sleep(8)
pag.press('alt')
time.sleep(1)
pag.press('right',presses=3)
time.sleep(1)
pag.press('t')
time.sleep(1)
pag.press('a')
time.sleep(1)
pag.press('i')
time.sleep(4)
pag.press('down')
time.sleep(1)
pag.press('enter')
time.sleep(4)
pag.press('del',presses=5)
time.sleep(3)
pag.write('outlet.txt')
time.sleep(4)
pag.press('tab',presses=3)
time.sleep(4)
pag.press('enter')








