import os
import tkinter as tk
import time
import pyautogui as pag



pag.hotkey('alt','tab')
time.sleep(2)
pag.hotkey('ctrl','/')
time.sleep(0.5)
pag.write('/nmcsi')
time.sleep(0.5)
pag.press('enter')
time.sleep(3)
pag.press('down',presses=4)
time.sleep(0.5)
pag.press('enter')
time.sleep(3)
pag.press('down',presses=2)
time.sleep(0.5)
pag.press('del',presses=4)
time.sleep(0.5)
pag.write('re')
time.sleep(0.5)
pag.press('tab',presses=3)
time.sleep(0.5)
pag.press('del',presses=4)
time.sleep(0.5)
pag.write('mh')
time.sleep(0.5)
pag.press('tab',presses=6)
time.sleep(0.5)
pag.press('del',presses=4)
time.sleep(0.5)
pag.write('4203')
time.sleep(0.5)
pag.press('down',presses=2)
time.sleep(0.5)
pag.press('del',presses=8)
time.sleep(0.5)
pag.write('17*')
time.sleep(0.5)
pag.press('down',presses=2)
time.sleep(0.5)
pag.press('del',presses=15)
time.sleep(0.5)
pag.write('01.04.2024')
time.sleep(0.5)
pag.press('f8')
time.sleep(5)
pag.press('f7')
time.sleep(0.5)
pag.press('down',presses=3)
time.sleep(0.5)
pag.press('enter')



