import subprocess
import pyautogui as pag
import time

subprocess.run('C:\\Users\\ksraj\\OneDrive\\Desktop\\saplogon.bat',shell=True)
time.sleep(10)
pag.hotkey('alt','space')
time.sleep(1)
pag.press('x')
time.sleep(3)
pag.write('mcsi')
time.sleep(5)
pag.press('enter')
time.sleep(5)
pag.press('down',presses=16)
time.sleep(3)
pag.press('enter')
time.sleep(3)
pag.press('up',presses=3)
time.sleep(2)
pag.write((pag.prompt(text='Enter sap code', title='MSG Box' , default='')))
time.sleep(3)
pag.press('down',presses=1)
time.sleep(2)
pag.press('del',presses=10)
time.sleep(2)
pag.write((pag.prompt(text='Enter from date', title='MSG Box' , default='')))
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.write((pag.prompt(text='Enter t0 date', title='MSG Box' , default='')))
time.sleep(2)
pag.press('f8')
time.sleep(2)
pag.press('f7')
time.sleep(2)
pag.press('down',presses=2)
time.sleep(2)
pag.press('enter')
