import subprocess
import pyautogui as pag
import time

subprocess.run('C:\\Users\\ksraj\\OneDrive\\Desktop\\saplogon.bat',shell=True)
time.sleep(10)
pag.hotkey('alt','space')
time.sleep(1)
pag.press('x')
time.sleep(3)
pag.hotkey('ctrl','/')
time.sleep(1)
pag.write('/nmcsi')
time.sleep(6)
pag.press('enter')
time.sleep(2)
pag.press('down',presses=6)
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('down',presses=2)
time.sleep(1)
pag.write('re')
time.sleep(1)
pag.press('tab',presses=3)
time.sleep(1)
pag.write('MH')
time.sleep(1)
pag.press('tab',presses=9)
time.sleep(1)
pag.write('T94')
time.sleep(1)
pag.press('tab',presses=9)
time.sleep(1)
pag.press('delete',presses=10)
time.sleep(2)
pag.write((pag.prompt(text='Enter Month', title='MSG Box' , default='')))
time.sleep(2)
pag.press('tab',presses=1)
time.sleep(1)
pag.press('delete',presses=11)
time.sleep(2)
pag.press('f8')
time.sleep(1)
pag.press('alt')
time.sleep(1)
pag.press('right',presses=5)
time.sleep(1)
pag.press('h')
time.sleep(1)
pag.press('c')
time.sleep(1)
pag.press('alt')
time.sleep(1)
pag.press('e')
time.sleep(1)
pag.press('x')
time.sleep(1)
