import subprocess
import pyautogui as pag
import time
import os


os.system('start sapshcut.exe -system=PRD -client=310 -user=00501203 -pw=Hallux@123')


time.sleep(10)
pag.hotkey('alt','space')
time.sleep(0.3)
pag.press('x')
#subprocess.run('C:\\Users\\ksraj\\OneDrive\\Desktop\\saplogon.bat',shell=True)
#time.sleep(10)
#pag.hotkey('alt','space')
#time.sleep(1)
#pag.press('x')
time.sleep(3)
pag.write('mcsi')
time.sleep(2)
pag.press('enter')
time.sleep(3)
pag.press('down',presses=16)
time.sleep(3)
pag.press('enter')
time.sleep(3)
pag.press('up',presses=3)
time.sleep(4)
pag.write((pag.prompt(text='Enter sap code', title='MSG Box' , default='')))
time.sleep(3)
pag.press('down',presses=1)
time.sleep(2)
pag.press('del',presses=20)
time.sleep(5)
pag.write((pag.prompt(text='Enter from month', title='MSG Box' , default='')))
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.write((pag.prompt(text='Enter t0 month', title='MSG Box' , default='')))
time.sleep(2)
pag.press('f8')
time.sleep(2)
pag.press('f7')
time.sleep(2)
pag.press('down',presses=2)
time.sleep(2)
pag.press('enter')
time.sleep(5)
pag.press('alt')
time.sleep(3)
pag.press('down',presses=5)
time.sleep(4)
pag.press('right')
time.sleep(3)
pag.press('enter')
