import subprocess
import pyautogui as pag
import time
import os


pag.hotkey('alt','tab')
time.sleep(1)
pag.hotkey('ctrl','/')
time.sleep(1)
pag.write('/nmcsi')
time.sleep(2)
pag.press('enter')
time.sleep(6)
pag.press('down',presses=4)
time.sleep(3)
pag.press('enter')
time.sleep(3)
pag.press('up',presses=2)
time.sleep(1)
pag.press('del',presses=10)
time.sleep(1)
pag.write('01.04.2024')
time.sleep(1)
pag.press('tab')
time.sleep(1)
pag.write('23.08.2024')
time.sleep(1)
pag.press('up',presses=7)
time.sleep(1)
pag.hotkey('shift','tab')
time.sleep(1)
pag.write('re')
time.sleep(1)
pag.press('tab',presses=3)
time.sleep(1)
pag.write('mh')
time.sleep(1)
pag.press('tab',presses=6)
time.sleep(1)
pag.write('4203')
