import webbrowser
import pyautogui as pag
import time

# webbrowser.open("https://spandan.indianoil.co.in/RetailNew/Login.jsp")
# time.sleep(10)
# pag.press('tab')
# time.sleep(2)
# pag.write('00501203')
# time.sleep(1)
# pag.press('tab',presses=3)
# pag.write((pag.prompt(text='Enter the capcha', title='MSG Box' , default='')))
# time.sleep(2)
pag.hotkey('alt','tab')
time.sleep(3)
for i in range(25):
    pag.press('pageup')
    time.sleep(1)
    pag.click(x=432, y=551)
    time.sleep(1)
    time.sleep(40)
    pag.click(x=1754, y=693)
    # pag.click(x=1751, y=774)
    time.sleep(30)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(1)
    pag.click(x=601, y=816)
    time.sleep(2)
    pag.write('Recommended for approval')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.press('space')
    time.sleep(10)
    pag.press('pagedown')
    time.sleep(3)
    # pag.click(x=969, y=966)
    # pag.click(x=999, y=1009)
    pag.click(x=973, y=1006)  #firefox lenovo
    # pag.click(x=980, y=968)
    time.sleep(3)
    pag.write(pag.prompt('enter OTP'))
    time.sleep(3)
    pag.press('tab')
    time.sleep(2)
    pag.press('tab')
    time.sleep(2)
    pag.press('enter')
    time.sleep(13)
    # pag.click(x=921, y=405)

    pag.press('enter')
    time.sleep(13)


