import webbrowser
import pyautogui as pag
import time


pag.hotkey('alt','tab')
time.sleep(2)
pag.press('tab',presses=2)
time.sleep(2)
pag.press('space')
time.sleep(1)
#Approver 1

pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(1)
pag.press('down')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab')
time.sleep(1)
pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(1)
pag.press('e')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab',presses=6)
time.sleep(1)
pag.press('space')
time.sleep(1)
pag.hotkey('shift','tab')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab',presses=3)
time.sleep(1)
pag.press('space')
for i in range(3):
    pag.hotkey('shift','tab')

#Approver 2
pag.press('space')
time.sleep(2)
pag.press('tab',presses=9)
time.sleep(1)
pag.press('space')
time.sleep(1)
pag.hotkey('shift','tab')
time.sleep(1)
pag.press('enter')


# approver 4
time.sleep(1)
pag.press('tab',presses=3)
time.sleep(1)
pag.press('space')
for i in range(3):
    pag.hotkey('shift','tab')

time.sleep(1)
pag.press('space')
time.sleep(1)
time.sleep(1)
pag.press('tab',presses=5)
time.sleep(1)
pag.press('space')
time.sleep(1)
time.sleep(1)
pag.hotkey('shift','tab')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab',presses=4)
time.sleep(1)


#Approver 6
time.sleep(4)
pag.press('tab',presses=2)
time.sleep(1)
pag.press('space')
time.sleep(2)
pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(1)
pag.press('down')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab')
time.sleep(1)
pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(1)
pag.press('e')
time.sleep(1)
pag.press('enter')
time.sleep(1)
pag.press('tab',presses=6)
time.sleep(1)
pag.press('space')
time.sleep(1)
pag.hotkey('shift','tab')
time.sleep(1)
pag.press('enter')
time.sleep(1)




