import webbrowser
import pyautogui as pag
import time


pag.hotkey('alt','tab')
time.sleep(0.3)
pag.press('tab',presses=4)
pag.press('space')
time.sleep(3)
pag.press('tab',presses=7)
time.sleep(3)
pag.press('space')
time.sleep(3)
pag.press('space')
time.sleep(3)
pag.press('tab',presses=28)
time.sleep(3)
pag.write((pag.prompt(text='Enter start date', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
pag.write((pag.prompt(text='Enter start time', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
time.sleep(0.3)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('o')
time.sleep(0.3)
pag.press('enter')
time.sleep(3)
pag.press('tab')
dep_place=pag.prompt(text='Enter Departure place', title='MSG Box' , default='')
time.sleep(1)
pag.write(dep_place)
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.write((pag.prompt(text='Enter arrival date', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
pag.write((pag.prompt(text='Enter arrival time', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('o')
time.sleep(5)
pag.press('enter')
time.sleep(5)
pag.press('tab')
time.sleep(5)
arr_place=pag.prompt(text='Enter Arrival place', title='MSG Box' , default='')
time.sleep(1)
pag.write(arr_place)
time.sleep(4)
pag.press('tab')
time.sleep(0.3)
pag.hotkey('alt','up')
time.sleep(0.3)
pag.press('up',presses=5)
time.sleep(0.3)
pag.press('enter')
time.sleep(3)
pag.press('tab')
time.sleep(0.3)
# pag.write('TN38AD2108')
# time.sleep(0.3)
pag.press('tab')
time.sleep(0.3)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('down')
time.sleep(0.3)
pag.press('enter')
time.sleep(5)
pag.press('tab')
time.sleep(0.3)
pag.write((pag.prompt(text='Enter Kms', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab',presses=6)
time.sleep(0.3)

pag.write((pag.prompt(text='Enter start date', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
pag.write((pag.prompt(text='Enter start time', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
time.sleep(0.3)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('o')
time.sleep(0.3)
pag.press('enter')
time.sleep(3)
pag.press('tab')
pag.write(arr_place)
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.write((pag.prompt(text='Enter arrival date', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
pag.write((pag.prompt(text='Enter arrival time', title='MSG Box' , default='')))
time.sleep(0.3)
pag.press('tab')
time.sleep(1)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('o')
time.sleep(5)
pag.press('enter')
time.sleep(5)
pag.press('tab')
pag.write(dep_place)
pag.press('tab')
time.sleep(5)
pag.hotkey('alt','up')
time.sleep(0.3)
pag.press('up',presses=5)
time.sleep(0.3)
pag.press('enter')
time.sleep(13)
pag.press('tab')
time.sleep(0.3)
# pag.write('TN38AD2108')
time.sleep(0.3)
pag.press('tab')
time.sleep(0.3)
pag.hotkey('alt','down')
time.sleep(0.3)
pag.press('down')
time.sleep(0.3)
pag.press('enter')
time.sleep(10)
pag.press('tab')
time.sleep(0.3)
pag.write((pag.prompt(text='Enter Kms', title='MSG Box' , default='')))
time.sleep(0.3)







