import pyautogui as pag
import time
import os


os.system('start sapshcut.exe -system=PRD -client=310 -user=00501203 -pw=Strut@234')

time.sleep(30)
pag.hotkey('alt','space')
time.sleep(0.3)
pag.press('x')
time.sleep(10)
pag.write('mcsi')
time.sleep(2)
pag.press('enter')
time.sleep(3)
pag.press('down',presses=4)
time.sleep(3)
pag.press('enter')
time.sleep(3)
pag.press('up',presses=2)
time.sleep(3)
pag.press('del',presses=20)
time.sleep(5)
pag.write((pag.prompt(text='Enter sales date', title='MSG Box' , default='')))
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.press('del',presses=2)
time.sleep(2)
pag.press('up',presses=7)
time.sleep(2)
pag.hotkey('shift','tab')
time.sleep(2)
pag.write('re')
time.sleep(2)
pag.press('tab',presses=3)
time.sleep(2)
pag.write('mh')
time.sleep(2)
pag.press('tab',presses=6)
time.sleep(2)
pag.write('4203')
time.sleep(2)
pag.press('tab',presses=6)
pag.write('17*')
time.sleep(2)
pag.press('f8')
time.sleep(2)
pag.press('alt')
time.sleep(2)
pag.press('left',presses=3)
time.sleep(2)
pag.press('h')
time.sleep(2)
pag.press('k')
time.sleep(2)
pag.press('alt')
time.sleep(2)
pag.press('e')
time.sleep(2)
pag.press('x')
time.sleep(2)
for i in range(7):
    pag.press('down')
    time.sleep(1)
    pag.press('space')
time.sleep(2)
pag.press('down')
time.sleep(2)
for i in range(2):
    pag.press('down')
    time.sleep(1)
    pag.press('space')
time.sleep(2)
pag.press('tab')
time.sleep(2)
pag.press('enter')
time.sleep(5)
pag.press('up')
time.sleep(5)
pag.press('enter')
time.sleep(5)
pag.press('enter')



