import pyautogui as pag
import time
import pyttsx3

pag.hotkey('alt', 'tab')
time.sleep(1)

for i in range(5):
    #line 1
    pag.click(x=62, y=612)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(5)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)
    # i=1
    # while i <= 1:
    #     # im = pag.screenshot("Full screen.png")
    #     try:
    #         res = pag.locateOnScreen("open.png", confidence=0.7)
    #         # print(res)
    #         action_but = pag.center(res)
    #         pag.click(action_but)
    #         # pag.click(x,y)
    #     except TypeError:
    #         i = 1
    #     else:
    #         break
    #
    #
    # for i in range(14):
    #     pag.press('tab')
    #     time.sleep(0.5)
    #line 2
    # time.sleep(2# )
    #line 2
    pag.click(x=62, y=657)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 3
    pag.click(x=62, y=712)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 4
    pag.click(x=62, y=755)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 5
    pag.click(x=62, y=800)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 6
    pag.click(x=62, y=855)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)



    #line 7
    pag.click(x=62, y=895)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 8
    pag.click(x=62, y=944)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)

    #line 9
    pag.click(x=62, y=998)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)


    #line 10
    pag.click(x=62, y=1041)
    time.sleep(1)
    pag.press('pagedown')
    time.sleep(2)
    pag.click(x=1444, y=904)
    time.sleep(3)
    pag.write('note')
    time.sleep(1)
    pag.press('down')
    time.sleep(1)
    pag.press('enter')
    time.sleep(1)
    pag.press('tab')
    time.sleep(1)
    pag.write('point observed during audit has been complied')
    time.sleep(1)
    pag.press('space',presses=20)
    time.sleep(1)
    pag.press('tab',presses=3)
    time.sleep(1)
    pag.click(x=980, y=900)
    time.sleep(1)
    pag.press('pageup')
    time.sleep(2)
    pag.click(x=979, y=1114)
    time.sleep(1)

    engine = pyttsx3.init()
    engine.say("The program has finished executing its time for you you to look into it and restart the program .")
    engine.runAndWait()
